Improvements for optivum-scrapper
dominik-korsa/timetable-api pull request #52
Opened 2024-12-10 15:39 UTC by Marioneq4958

2024-12-10 18:23 UTC, Marioneq4958 commented
#53

2024-12-21 10:47 UTC, dominik-korsa requested changes

2024-12-21 10:47 UTC, dominik-korsa commented on packages/optivum-scrapper/src/timetable.ts
> +        };
Obecnie czasami ta funkcja zwraca `undefined`

```suggestion
        const isMatchingLesson = (existingLesson: ClientLesson): boolean => {
            // Comment
            if (existingLesson.type === 'comment') return false;

            // Lessons without interclass groups (by teacher)
            if (lesson.teacherId !== null && existingLesson.teacherId !== null)
                return lesson.teacherId === existingLesson.teacherId;

            // Interclass groups
            if (lesson.subjectId !== existingLesson.subjectId) return false;
            // Interclass groups: class tables
            if (lesson.interclassGroupId !== null && existingLesson.interclassGroupId !== null)
                return lesson.interclassGroupId === existingLesson.interclassGroupId;
            // Interclass groups: teacher tables
            if (unit.type !== UnitType.CLASS)
                return [...existingLesson.classIds.values()].find((classId) => lesson.classIds.has(classId));
            
            return false;
        };
```

2024-12-21 10:47 UTC, dominik-korsa commented on packages/optivum-scrapper/src/timetable.ts
> +            commonGroups = new Map([...commonGroups, ...parsedTable.groups]);
Niepotrzebnie tworzysz nowe Sety i Mapy za każdym razem, wystarzyłoby modyfikować istniejące. Tak robisz poniżej:
```ts
lesson.classIds.forEach((classId) => existingLesson.classIds.add(classId));
lesson.groupIds.forEach((groupId) => existingLesson.groupIds.add(groupId));
```
Możesz stworzyć jakieś uniwersalne funkcje do tego. Co jeżeli powtarzy się klucz w Mapie?

2024-12-21 11:51 UTC, dominik-korsa approved these changes

2024-12-21 11:51 UTC, merged